function createfigure(X1, Y1, E1)
%CREATEFIGURE(X1,Y1,E1)
%  X1:  errorbar x
%  Y1:  errorbar y
%  E1:  errorbar e

%  Auto-generated by MATLAB on 08-Aug-2011 11:18:29

% Create figure
figure1 = figure('XVisual',...
    '0xd5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTick',[6 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80],...
    'XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[6 80]);
box(axes1,'on');
hold(axes1,'all');

% Create title
title('Number of Slots in Sync Phase with density: 83 AN/Km²');

% Create errorbar
errorbar(X1,Y1,E1,'LineWidth',2,'Color',[0 0 1]);

% Create xlabel
xlabel('Number of randomly uniformly distributed Anchors');

% Create ylabel
ylabel('Number of Slots in Sync Phase');

