function createfigure1(X1, Y1, E1)
%CREATEFIGURE1(X1,Y1,E1)
%  X1:  errorbar x
%  Y1:  errorbar y
%  E1:  errorbar e

%  Auto-generated by MATLAB on 08-Aug-2011 11:23:02

% Create figure
figure1 = figure('XVisual',...
    '0xd5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'Name','Number of Slots in Sync Phase with the number of Anchors in 1 Km2',...
    'Color',[1 1 1]);
colormap('summer');

% Create axes
axes1 = axes('Parent',figure1,...
    'YTick',[0 2 4 6 8 10 12 14 16 18 20 22 24 25],...
    'YGrid','on',...
    'XTick',[2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70],...
    'XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2 70]);
box(axes1,'on');
hold(axes1,'all');

% Create title
title('Number of Slots in Sync Phase with the number of Anchors in 1 Km²');

% Create errorbar
errorbar(X1,Y1,E1,'LineWidth',1,'Color',[0 0 1]);

% Create xlabel
xlabel('Number of randomly uniformly distributed Anchors');

% Create ylabel
ylabel('Number of Slots in Sync Phase');

