function Create_average_time_between_arrivals_figure(YMatrix1, EMatrix1)
%CREATEFIGURE(YMATRIX1,EMATRIX1)
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix

%  Auto-generated by MATLAB on 30-Mar-2011 10:18:34

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 31],...
    'XGrid','on',...
    'Position',[0.13 0.110154905335628 0.775 0.81411359724613]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 31]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.002 0.011]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(YMatrix1,EMatrix1,'LineWidth',2);
set(errorbar1(1),'DisplayName','With hidden terminal problem');
set(errorbar1(2),'DisplayName','Avoiding hidden terminal problem',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('Max. Random time between transmissions (ms)');

% Create ylabel
ylabel('Average time between consecutive arriving packets (s)');

% Create legend
legend(axes1,'show');

