function Create_average_different_times_figure(YMatrix1, EMatrix1, YMatrix2, EMatrix2)
%CREATEFIGURE(YMATRIX1,EMATRIX1,YMATRIX2,EMATRIX2)
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix
%  YMATRIX2:  errorbar y matrix
%  EMATRIX2:  errorbar e matrix

%  Auto-generated by MATLAB on 30-Mar-2011 11:04:50

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'Position',[0.13 0.111721170395869 0.334659090909091 0.815]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.08]);
box(axes1,'on');
hold(axes1,'all');

% Create title
title('Avoiding hidden terminal problem');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(YMatrix1,EMatrix1,'LineWidth',2);
set(errorbar1(1),'DisplayName','Last packet');
set(errorbar1(2),'DisplayName','Last 3rd packet','Color',[0 0 0]);
set(errorbar1(3),'DisplayName','Last 2nd packet',...
    'Color',[0 0.498039215803146 0]);
set(errorbar1(4),'DisplayName','Last 1st packet','Color',[0 1 0]);
set(errorbar1(5),'DisplayName','First packet','Color',[1 0 0]);

% Create xlabel
xlabel('Max. Random time between transmissions');

% Create ylabel
ylabel('Average packet arrival time');

% Create axes
axes2 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'Position',[0.570340909090909 0.110154905335628 0.334659090909091 0.816566265060241]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 0.08]);
box(axes2,'on');
hold(axes2,'all');

% Create title
title('With hidden terminal problem');

% Create multiple error bars using matrix input to errorbar
errorbar2 = errorbar(YMatrix2,EMatrix2,'LineWidth',2);
set(errorbar2(1),'DisplayName','Last packet');
set(errorbar2(2),'DisplayName','Last 3rd packet','Color',[0 0 0]);
set(errorbar2(3),'DisplayName','Last 2nd packet',...
    'Color',[0 0.498039215803146 0]);
set(errorbar2(4),'DisplayName','Last 1st packet','Color',[0 1 0]);
set(errorbar2(5),'DisplayName','First packet','Color',[1 0 0]);

% Create xlabel
xlabel('Max. Random time between transmissions');

% Create ylabel
ylabel('Average packet arrival time');

