function Create_percentil_98_different_times(YMatrix1, YMatrix2)
%CREATEFIGURE(YMATRIX1,YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 30-Mar-2011 12:03:45

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1,'YGrid','on','XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[1 30]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 0.15]);
box(subplot1,'on');
hold(subplot1,'all');

% Create title
title('Avoiding hidden terminal problem');

% Create xlabel
xlabel('Max. Random time between transmissions');

% Create ylabel
ylabel('Percentil 98% packet arrival time');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'Color',[1 0 0],'DisplayName','First packet');
set(plot1(2),'Color',[0 1 0],'DisplayName','Last 1st packet');
set(plot1(3),'Color',[0 0.498039215803146 0],...
    'DisplayName','Last 2nd packet');
set(plot1(4),'DisplayName','Last 3rd packet','Color',[0 0 0]);
set(plot1(5),'Color',[0 0 1],'DisplayName','Last packet');

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1,'YGrid','on','XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[1 30]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 0.15]);
box(subplot2,'on');
hold(subplot2,'all');

% Create title
title('With hidden terminal problem');

% Create xlabel
xlabel('Max. Random time between transmissions');

% Create ylabel
ylabel('Percentil 98% packet arrival time');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2,'LineWidth',2);
set(plot2(1),'Color',[1 0 0],'DisplayName','First packet');
set(plot2(2),'Color',[0 1 0],'DisplayName','Last 1st packet');
set(plot2(3),'Color',[0 0.498039215803146 0],...
    'DisplayName','Last 2nd packet');
set(plot2(4),'DisplayName','Last 3rd packet','Color',[0 0 0]);
set(plot2(5),'Color',[0 0 1],'DisplayName','Last packet');

% Create legend
legend1 = legend(subplot2,'show');
set(legend1,...
    'Position',[0.580210517120895 0.748733027347486 0.197458071278826 0.167096959265634]);

% Create legend
legend2 = legend(subplot1,'show');
set(legend2,...
    'Position',[0.139958944793851 0.748733027347486 0.197458071278826 0.167096959265634]);

