function Received_packets_and_last_packet_arrival(YMatrix1, EMatrix1, YMatrix2, EMatrix2)
%CREATEFIGURE(YMATRIX1,EMATRIX1,YMATRIX2,EMATRIX2)
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix
%  YMATRIX2:  errorbar y matrix
%  EMATRIX2:  errorbar e matrix

%  Auto-generated by MATLAB on 30-Mar-2011 12:38:54

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'YGrid','on',...
    'YColor',[1 0 0],...
    'XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 30]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 24]);
box(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel('Max Random time between transmissions');

% Create ylabel
ylabel('Received Packets','Color',[1 0 0]);

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(YMatrix1,EMatrix1,'LineWidth',2);
set(errorbar1(1),...
    'DisplayName','Received packets avoiding hidden terminal problem',...
    'Color',[1 0 0]);
set(errorbar1(2),...
    'DisplayName','Received packets with hidden terminal problem',...
    'Color',[0.749019622802734 0.749019622802734 0]);

% Create axes
axes2 = axes('Parent',figure1,...
    'YTick',[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16],...
    'YAxisLocation','right',...
    'YColor',[0 0 1],...
    'ColorOrder',[0 0.5 0;1 0 0;0 0.75 0.75;0.75 0 0.75;0.75 0.75 0;0.25 0.25 0.25;0 0 1],...
    'Color','none');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1 30]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.01 0.16]);
hold(axes2,'all');

% Create ylabel
ylabel('Last packet arrival time (s)','VerticalAlignment','cap',...
    'Color',[0 0 1]);

% Create multiple error bars using matrix input to errorbar
errorbar2 = errorbar(YMatrix2,EMatrix2,'LineWidth',2);
set(errorbar2(1),...
    'DisplayName','Last packet arrival time avoiding hidden terminal problem',...
    'Color',[0 0 1]);
set(errorbar2(2),...
    'DisplayName','Last packet arrival time with hidden terminal problem',...
    'Color',[0.749019622802734 0 0.749019622802734]);

% Create legend
legend1 = legend(axes2,'show');
set(legend1,...
    'Position',[0.405682215234103 0.118692329873131 0.49148322851153 0.135801134179162]);

