//
// Generated file, do not edit! Created by opp_msgc 4.1 from messages/ApplPkt.msg.
//

#ifndef _APPLPKT_M_H_
#define _APPLPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/ApplPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet ApplPkt
 * {
 *     int sequenceId = 0;				
 *     int destAddr = -1; 				
 *     int srcAddr = -1; 				
 *     int priority = 0; 				
 *     int8 status = 0;
 * 	int16 posX = 0;
 * 	int16 posY = 0;
 * 	int16 posZ = 0;
 * 	int32 timestamp = 0;
 * 	
 * 	
 * 	int realDestAddr = -1;
 * 	int realSrcAddr = -1;
 * 	int retransmisionCounter = 0;	
 * 	bool CSMA; 						
 * 	bool askForRequest;				
 * 	bool requestPacket;				
 * }
 * </pre>
 */
class ApplPkt : public ::cPacket
{
  protected:
    int sequenceId_var;
    int destAddr_var;
    int srcAddr_var;
    int priority_var;
    int8 status_var;
    int16 posX_var;
    int16 posY_var;
    int16 posZ_var;
    int32 timestamp_var;
    int realDestAddr_var;
    int realSrcAddr_var;
    int retransmisionCounter_var;
    bool CSMA_var;
    bool askForRequest_var;
    bool requestPacket_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ApplPkt&);

  public:
    ApplPkt(const char *name=NULL, int kind=0);
    ApplPkt(const ApplPkt& other);
    virtual ~ApplPkt();
    ApplPkt& operator=(const ApplPkt& other);
    virtual ApplPkt *dup() const {return new ApplPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSequenceId() const;
    virtual void setSequenceId(int sequenceId_var);
    virtual int getDestAddr() const;
    virtual void setDestAddr(int destAddr_var);
    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr_var);
    virtual int getPriority() const;
    virtual void setPriority(int priority_var);
    virtual int8 getStatus() const;
    virtual void setStatus(int8 status_var);
    virtual int16 getPosX() const;
    virtual void setPosX(int16 posX_var);
    virtual int16 getPosY() const;
    virtual void setPosY(int16 posY_var);
    virtual int16 getPosZ() const;
    virtual void setPosZ(int16 posZ_var);
    virtual int32 getTimestamp() const;
    virtual void setTimestamp(int32 timestamp_var);
    virtual int getRealDestAddr() const;
    virtual void setRealDestAddr(int realDestAddr_var);
    virtual int getRealSrcAddr() const;
    virtual void setRealSrcAddr(int realSrcAddr_var);
    virtual int getRetransmisionCounter() const;
    virtual void setRetransmisionCounter(int retransmisionCounter_var);
    virtual bool getCSMA() const;
    virtual void setCSMA(bool CSMA_var);
    virtual bool getAskForRequest() const;
    virtual void setAskForRequest(bool askForRequest_var);
    virtual bool getRequestPacket() const;
    virtual void setRequestPacket(bool requestPacket_var);
};

inline void doPacking(cCommBuffer *b, ApplPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ApplPkt& obj) {obj.parsimUnpack(b);}


#endif // _APPLPKT_M_H_
