//
// Generated file, do not edit! Created by opp_msgc 4.1 from messages/MacPkt.msg.
//

#ifndef _MACPKT_M_H_
#define _MACPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/MacPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet MacPkt
 * {
 *     long destAddr; 
 *     long srcAddr;  
 *     long sequenceId; 
 * }
 * </pre>
 */
class MacPkt : public ::cPacket
{
  protected:
    long destAddr_var;
    long srcAddr_var;
    long sequenceId_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacPkt&);

  public:
    MacPkt(const char *name=NULL, int kind=0);
    MacPkt(const MacPkt& other);
    virtual ~MacPkt();
    MacPkt& operator=(const MacPkt& other);
    virtual MacPkt *dup() const {return new MacPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual long getDestAddr() const;
    virtual void setDestAddr(long destAddr_var);
    virtual long getSrcAddr() const;
    virtual void setSrcAddr(long srcAddr_var);
    virtual long getSequenceId() const;
    virtual void setSequenceId(long sequenceId_var);
};

inline void doPacking(cCommBuffer *b, MacPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MacPkt& obj) {obj.parsimUnpack(b);}


#endif // _MACPKT_M_H_
